### ISSUE TITLE
Fail to install the package

### ISSUE THREAD

**Issue by 54610a** [stla/cgalMeshes#15]
Hello,

Firstly, thanks a lot for this excellent package!

I am a beginner in R, and want to install this package. I am using R 4.3.1 and has already installed rtools 43. 

I installed with `remotes::install_github("stla/cgalMeshes@github", dependencies = TRUE, build_vignettes = TRUE)` as recommended. 

While installing this package, an error occurred, and I tried to search it on the internet and still have no clue. The error is the following:

```
   AFSreconstruction.cpp:17:0: required from here
   D:/Tools/R-4.3.1/library/BH/include/boost/container/detail/copy_move_algo.hpp:226:19:warning: void* memmove(void*, const void*, size_t)writing to an object of type 'value_type{aka 'struct std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Advancing_front_surface_reconstruction_cell_base_3<CGAL::Epick, CGAL::Delaunay_triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Advancing_front_surface_reconstruction_vertex_base_3<CGAL::Epick>, CGAL::Advancing_front_surface_reconstruction_cell_base_3<CGAL::Epick> > > > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, int>th no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess
     226 |       std::memmove(dest_raw, beg_raw, sizeof(value_type)*n)
         |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   In file included from d:\tools\rtools43\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\12.2.0\include\c++\bits\stl_algobase.h:64
                    from d:\tools\rtools43\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\12.2.0\include\c++\bits\specfun.h:45
                    from d:\tools\rtools43\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\12.2.0\include\c++\cmath:1935
                    from D:/Tools/R-4.3.1/library/Rcpp/include/Rcpp/platform/compiler.h:100
   d:\tools\rtools43\x86_64-w64-mingw32.static.posix\lib\gcc\x86_64-w64-mingw32.static.posix\12.2.0\include\c++\bits\stl_pair.h:185:12:note: value_type{aka 'struct std::pair<CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Advancing_front_surface_reconstruction_cell_base_3<CGAL::Epick, CGAL::Delaunay_triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_cell_base_3<CGAL::Epick, CGAL::Triangulation_ds_cell_base_3<CGAL::Triangulation_data_structure_3<CGAL::Advancing_front_surface_reconstruction_vertex_base_3<CGAL::Epick>, CGAL::Advancing_front_surface_reconstruction_cell_base_3<CGAL::Epick> > > > > >, CGAL::Default, CGAL::Default, CGAL::Default>, false>, int>clared here
     185 |     struct pair
         |            ^~~~
   make: *** [D:/Tools/R-4.3.1/etc/x64/Makeconf:272: AFSreconstruction.o] Error 1
   ERROR: compilation failed for package 'cgalMeshes'
─  removing 'C:/Users/LIUYUL~1/AppData/Local/Temp/RtmpuaoyxG/Rinst27fc44ce4f8e/cgalMeshes'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'cgalMeshes' from GitHub:
  ! System command 'Rcmd.exe' failed
```

The text in the console of Rstudio is veeeery long (I don't know whether it is normal).  I don't know exactly what part of it is important, and above is the last part of it. I have attatched the full error information below, it is really long. 
[Error Information.txt](https://github.com/stla/cgalMeshes/files/12442089/Error.Information.txt)

I have installed Visual Studio 2022, and have installed CGAL. I have tried to search it on the internet and still have no clue. I didn't see anyone who face the same situation as I do. I would appreciate it a lot if you could help me out. 

Thanks a lot in advance

Best wishes,

Yulin

**Comment by stla** [comment]
Sorry, I'm not very familiar with C++. And this is not the only issue. I think I will build a zip version of the package and make it available here.

**Comment by 54610a** [comment]
Thank you very much! That's a great help to me! Hope to see your package on CRAN soon! 
Best wishes!

**Comment by stla** [comment]
Hello @54610a 

I uploaded a zip [here](https://github.com/stla/cgalMeshes/releases/tag/Github_v3.1.0). Please say me whether it works.

**Comment by 54610a** [comment]
It worked! Thank you very much! I can find it in the package window, but the information below occurred, so I am not sure whether it is correctly installed. I'll create new issues later if I meet other problems. 
>files ‘essais/Enneper.R’, ‘essais/FermatSpiral.png’, ‘essais/HEART_OBS5.ply’, ‘essais/Mesh3D.cpp’, ‘essais/Toratope7D_cgalMeshes.R’, ‘essais/alphaWrapping.Rmd’, ‘essais/alphaWrapping.html’, ‘essais/alphaWrappingRmd.R’, ‘essais/benchmarks.R’, ‘essais/clean-Rd.R’, ‘essais/clean-Rd2.R’, ‘essais/clean-Rd3.R’, ‘essais/clippedCylinders.R’, ‘essais/dfdr_BonanJeenerKlein.R’, ‘essais/dfdr_twistedSphere.R’, ‘essais/diplodocus.off’, ‘essais/essai-ReadWrite.R’, ‘essais/essai-alphaWrap-teapot.R’, ‘essais/essai-alphaWrap-teapot2.R’, ‘essais/essai-bigPolyhedron.R’, ‘essais/essai-boundsVolume.R’, ‘essais/essai-bunny.R’, ‘essais/essai-clip.R’, ‘essais/essai-convexParts.R’, ‘essais/essai-dilationxy.R’, ‘essais/essai-diplodocus.R’, ‘essais/essai-dragon.R’, ‘essais/essai-dragon2.R’, ‘essais/essai-dragon3.R’, ‘essais/essai-dual-platonic.R’, ‘essais/essai-dual.R’, ‘essais/essai-fair.R’, ‘essais/essai-frog.R’, ‘essais/essai-geoDists.R’, ‘essais/essai-geoDists2.R’, ‘essais/essai-gyroid.R’, ‘essais/essai-hopf-union.R’, ‘essais/essai-hopf-venom.R’, ‘essais/essai-intersection.R’, ‘essais/essai-optimalBoundingBox.R’, ‘essais/essai-param-CostaMesh.R’, ‘essais/essai-param-MobiusCheckerboard.R’, ‘essais/essai-param-conformal-squareBorder1.R’, ‘essais/essai-param-conformal-squareBorder2.R’, ‘essais/essai-param-conformal.R’, ‘essais/essai-param-conformal2.R’, ‘essais/essai-param-conformal3.R’, ‘essais/essai-param-conformal4.R’, ‘essais/essai-param-conformal5.R’, ‘essais/essai-param-conformal6.R’, ‘essais/essai-param-conformal7.R’, ‘essais/essai-param-conformal8.R’, ‘essais/essai-param-conformal9.R’, ‘essais/essai-param-half-soccerStar.R’, ‘essais/essai-param-map-FermatSpiral.R’, ‘essais/essai-param-map-schmidt-halfHopfTorus.R’, ‘essais/essai-param-map-schmidt-halfSoccerStar.R’, ‘essais/essai-param-map-schmidt.R’, ‘essais/essai-param-radialCheckerboard.R’, ‘essais/essai-param-sudanesMobiusBand.R’, ‘essais/essai-param-togliatti.R’, ‘essais/essai-paramdirect-sphericalCap.R’, ‘essais/essai-parameterization01.R’, ‘essais/essai-parametricMesh-color.R’, ‘essais/essai-pentagrammicPrism_selfintersecting.R’, ‘essais/essai-removeSelfIntersections.R’, ‘essais/essai-removeSelfIntersections_heart5.R’, ‘essais/essai-smoothAngle.R’, ‘essais/essai1.R’, ‘essais/essai_Minkowski.R’, ‘essais/essai_Poisson.R’, ‘essais/essai_SSSreconstruction.R’, ‘essais/essai_gatherVertices.R’, ‘essais/essai_samplingInMesh.R’, ‘essais/essai_smoothing.R’, ‘essais/essais-smoothShape-HopfTorus.R’, ‘essais/htetrahedron.R’, ‘essais/knotMesh.R’, ‘essais/mesh_1.ply’, ‘essais/mesh_2.ply’, ‘essais/oloid.R’, ‘essais/oloid2.R’, ‘essais/parametricMesh.R’, ‘essais/reflection.R’, ‘essais/reflection2.R’, ‘essais/reflection3.R’, ‘essais/schmidt2_square.png’, ‘essais/schmidt3_square.png’, ‘essais/schmidt_square.png’, ‘essais/teapot.obj’, ‘essais/test-orbifold-barth.R’, ‘essais/test-orbifold-soccerStar.R’, ‘essais/vignette-Enneper.R’, ‘essais/voxel2mesh.R’, ‘keep/MODULE.h’, ‘keep/atest_parameterization.cpp’, ‘keep/gatherVertices.cpp’, ‘keep/runifHexahedron.cpp’, ‘keep/testclip.R’, ‘keep/writeFile.cpp’, ‘screenshots/Enneper-radialCheckerboard-DCP.gif’, ‘screenshots/HopfTorus.gif’, ‘screenshots/Hopf_LoopSubdivision.png’, ‘screenshots/SphericalCap-FermatSpiral.gif’, ‘screenshots/Togliatti-DCP.gif’, ‘screenshots/clippedCylinders.gif’, ‘screenshots/dragon.png’, ‘screenshots/halfHopfTorus-Schmidt.gif’, ‘screenshots/holeFilling.png’, ‘screenshots/knot-2-5.gif’, ‘screenshots/oloid.gif’, ‘screenshots/trefoilKnot.gif’, ‘trash/AA.cpp’, ‘trash/Enneper-Doyle.gif’, ‘trash/FermatSpiral_square.png’, ‘trash/SphericalCap-FermatSpiral_square.gif’, ‘trash/doyle_9-16.png’, ‘trash/essai-param-map-doyle.R’, ‘trash/figure8.gif’, ‘trash/septuaginta.png’, ‘trash/sphericalCap-Fermat.png’ are missing

**Comment by stla** [comment]
Ah these are some files I deleted after the zip has been created, because they are not needed and the zip was > 40Mo. Apparently the built stores the paths of the existing files.

Do you know whether the vignette works?
