### ISSUE TITLE
Wish: Poisson reconstruction

### ISSUE THREAD

**Issue by dwoll** [stla/cgalMeshes#3]
Sorry for keeping you on your toes with new issues! It's great to see such a high responsiveness to user feedback. Anyway, having reconstruction capability in `cgalMeshes` is really convenient. If it's not too hard to carry the Poisson reconstruction over from the `SurfaceReconstruction` package as well (in addition to AFS, as already implemented), it would be very nice.

I'd like to down-sample structures on import to speed up further calculations - mainly during testing of new features, and Poisson sampling was really good for this. Certainly not essential, but convenient. Thanks in advance!

**Comment by stla** [comment]
Me too I like the Poisson reconstruction. Unfortunately it throws a C++ warning, that's why CRAN has removed my package **SurfaceReconstruction**.

**Comment by dwoll** [comment]
Ah, I see. No worries.

**Comment by stla** [comment]
Hello @dwoll 

I decided to develop the package in a non-master branch (the **github** branch) to add the features unacceptable for CRAN. I already added the Poisson reconstruction. To install the package from this branch:

```r
remotes::install_github("stla/cgalMeshes@github")
```

Also take a look at the new features (available in both branches): [NEWS.md](https://github.com/stla/cgalMeshes/blob/main/NEWS.md).

Cheers.

**Comment by dwoll** [comment]
Cool, thank you very much!

**Comment by stla** [comment]
Hello @dwoll 

Just added two methods for the Hausdorff distance (in the **github** branch).

**Comment by dwoll** [comment]
Many thanks! I checked against `Rvcg::vcgMetro()`, and it gives the same results.
