### ISSUE TITLE
Failure reading PLY file

### ISSUE THREAD

**Issue by dwoll** [stla/cgalMeshes#6]
Hi, Thank you very much for further developing cgalMeshes! Using the current GitHub version (1.1.0) with the github branch, I see the following issue:

```
library(cgalMeshes)
mesh <- cgalMesh$new("Obs02_HEART.ply")
```

With cgalMeshes 1.0.0, this works with a warning: "Some duplication happened during polygon soup orientation". With version 1.1.0, this results in the error "reading failure".

[Obs02_HEART.txt](https://github.com/stla/cgalMeshes/files/10720040/Obs02_HEART.txt)

**Comment by stla** [comment]
Ok. I think the PLY reader only accepts "valid" meshes. I will take a look. But you can read this mesh with the **Rvcg** package:
```r
Rvcg::vcgPlyRead("Obs02_HEART.ply")
```
This indicates there's a duplicate face, that should be the reason of the failure.

**Comment by dwoll** [comment]
Great, thanks!

**Comment by stla** [comment]
Now you can read this file by doing:
```r
mesh <- cgalMesh$new("Obs02_HEART.ply", clean = TRUE)
```
There's a warning but it works.  The pay to price is that the normals and the colors, if present in the PLY file, are lost.
