### ISSUE TITLE
Error in getMesh(normals =FALSE)

### ISSUE THREAD

**Issue by dwoll** [stla/cgalMeshes#7]
Again, thanks for continuing to work on cgalMeshes! With the current devel version 1.1.0 in the github branch, I see this error:

```
library(cgalMeshes)
mesh1 <- cgalMesh$new("Obs01_HEART.ply")
mesh1$getMesh(rgl=TRUE, normals=FALSE)
```

With cgalMeshes version 1.0.0, this runs fine. With version 1.1.0, I get an error about `normals` matching multiple arguments. Removing `normals=FALSE` fixes the issue.

[Obs01_HEART.txt](https://github.com/stla/cgalMeshes/files/10720066/Obs01_HEART.txt)

**Comment by stla** [comment]
Hello. I'm surprised this option is still there. To get the normals with 1.1.0, you have to do:

```r
mesh1$computeNormals()
mesh1$getMesh()
```

**Comment by dwoll** [comment]
Thanks! I see I should have waited a couple of days, now reading what looks like a TODO indicator at
https://github.com/stla/cgalMeshes/blob/49e39f82174e93c1eba946d02578a0c826ea8448/R/cgalMesh.R#L1073

**Comment by stla** [comment]
Lol, I totally forgot that. Thanks!
