### ISSUE TITLE
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) :    Cannot add face 2429. 

### ISSUE THREAD

**Issue by Jsalas424** [stla/cgalMeshes#8]
Hello,

I've been using the following code to visualize meshes that have been externally generated. 

```
cgalMesh$new(vertices = as.matrix(vertices[,1:3]),
                   faces = as.matrix(faces[,1:3]))
```

So far, it's been working great and has then allowed me to manipulate the mesh as necessary. I've run into an issue.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/51519895/218583055-a9241b11-52e8-4664-9a40-c46117b454ea.png">

I can recreate the mesh using rgl::mesh3d()

```
mesh <- mesh3d(vertices = as.matrix(vertices[,1:3]) |> t(),
                     triangles = as.matrix(faces[,1:3] |> t()))
```
<img width="431" alt="image" src="https://user-images.githubusercontent.com/51519895/218602317-ffadbf4c-b3c4-43c4-abd4-1cae102286aa.png">

If I try to make the object with rgl and then pass it through to cgalMeshes, we recreate the same error:

```
> mesh <- cgalMesh$new(mesh)
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Cannot add face 2429.
```

Data in R format:

vertices: https://pastebin.com/gkWwLq60
faces: https://pastebin.com/Y0WK7yzU

I can upload .rmd files as well.

**Comment by Jsalas424** [comment]
I made a .mat file including the data for easy reproduction. 

```
>> load('/Users/.../cgalmesh_issue.mat')
>> tr = triangulation(faces, vertices(:,1), vertices(:,2), vertices(:,3));
Warning: Some input points are not referenced by the triangulation. 
>> trisurf(tr)
```

[cgalmesh_issue.mat.zip](https://github.com/stla/cgalMeshes/files/10726826/cgalmesh_issue.mat.zip)

**Comment by stla** [comment]
Hello,

This mesh is not "clean" -> use the `clean = TRUE` option. There's a warning but it works.

`Rvcg::vcgClean` shows it is not clean : try 
```r
rmesh <- rgl::tmesh3d(
  vertices = t(vertices),
  indices  = t(faces),
  homogeneous = FALSE
)

Rvcg::vcgClean(rmesh, sel = 0:7)
```

**Comment by Jsalas424** [comment]
> Hello,
> 
> 
> 
> This mesh is not "clean" -> use the `clean = TRUE` option. There's a warning but it works.
> 
> 
> 
> `Rvcg::vcgClean` shows it is not clean : try 
> 
> ```r
> 
> rmesh <- rgl::tmesh3d(
> 
>   vertices = t(vertices),
> 
>   indices  = t(faces),
> 
>   homogeneous = FALSE
> 
> )
> 
> 
> 
> Rvcg::vcgClean(rmesh, sel = 0:7)
> 
> ```

Thanks for the reply! I'm assuming you're referring to a clean = TRUE option that I can declare in your $new call, or need I preprocess with Rvcg first?

**Comment by stla** [comment]
In the `$new` call.

**Comment by Jsalas424** [comment]
Can you explain a little what "Warning: Polygon orientation failed. means?  Otherwise it looks like that fixed the issue, thanks!

**Comment by stla** [comment]
The faces of a mesh have an orientation (for example (A,B,C) and (B,A,C) have opposite orientations).  If a face is not correctly oriented and if the mesh has normals, then if you plot the mesh you will get some black color instead of the desired color. I don't know how CGAL automatically finds the orientations, but here it reports an unsuccessful orientation.

**Comment by stla** [comment]
But I don't see any problem when I plot this mesh in spite of this warning.

**Comment by Jsalas424** [comment]
Am I to understand that this would matter more if my faces had colors? The one's I'm working with currently do not.

**Comment by stla** [comment]
The color argument of `rgl::shade3d` defines the color. I tried `shade3d(yourMesh, color = "red")` and I didn't see any problem. There's always a color.

Moreover, once you have the rgl mesh (with `$getMesh`), you can try to pass it to the `$new` method and there's no problem, no need of `clean = TRUE`. 

So I'm not sure to understand. Maybe the orientation fails but it is nevertheless correct by luck? I don't know honnestly.

**Comment by Jsalas424** [comment]
> The color argument of `rgl::shade3d` defines the color. I tried `shade3d(yourMesh, color = "red")` and I didn't see any problem. There's always a color.
> 
> Moreover, once you have the rgl mesh (with `$getMesh`), you can try to pass it to the `$new` method and there's no problem, no need of `clean = TRUE`.
> 
> So I'm not sure to understand. Maybe the orientation fails but it is nevertheless correct by luck? I don't know honnestly.

I appreciate you speculating nonetheless!

**Comment by stla** [comment]
Moreover `Rvcg::checkFaceOrientation` and `Rvcg::meshintegrity` do not detect any problem regarding the rgl mesh.
